- name: Install Longhorn using helm
  hosts: longhorn_deployments
  connection: local
  gather_facts: false

  tasks:
    - name: Add longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    - name: Deploy Longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        namespace: longhorn-system
        update_repo_cache: true
        create_namespace: true
        kubeconfig: /tmp/rke2.yaml
        wait: true
        set_values:
          - value: "service.ui.type=LoadBalancer"
          - value: "ingress.enabled=true"
